spring:
  profiles:
     active: dev
  jackson:
     date-format: dd-MM-yyyy HH:mm:ss
     time-zone: GMT+3
     default-property-inclusion: non_null
     parser:
        allow_unquoted_field_names: true
     serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
