flyway:
    baseline-on-migrate: true
    baseline-version: 0
    check-location: false
    enabled: true
    locations: classpath:db/migration
spring:
    datasource:
        character: utf-8
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://54.194.136.97:5432/projectstatus
        username: postgres
        password: postgres
        dbcp2:
           initial-size: 10
           max-total: 20
           pool-prepared-statements: true
           test-on-borrow: true
           validation-query: SELECT 1
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: false

server:
    port: 9797
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

